In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
 import numpy as n
arr=n.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as n
arr=n.ones((5,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np
arr=np.full((4,7),9)
arr

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [ ]:
import numpy as np
arr=np.empty((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
arr=np.arange(1,100)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
import numpy as np
arr=np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
import numpy as np
arr=np.arange(2,200,2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198])

In [ ]:
import numpy as np
Even=np.arange(2,200,2)
print(Even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [ ]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np
arr=np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.94029995 0.51322473 0.57628637 0.26149638 0.96555138 0.4371156
 0.61596069 0.68001413 0.88642037 0.94984369]


In [ ]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[ 1.51738515  2.08330767 -0.16411568 -0.64369762 -0.10509016  0.48826558
  0.49054135 -1.34427984  0.55849373 -1.38815091]


In [ ]:
import numpy as np
arr=np.random.randint(100)
print(arr)

68


In [ ]:
import numpy as np
colours=["red","green","pink","orange","blue",'white',"black"]
print(np.random.choice(colours,2))

['black' 'pink']


In [ ]:
import numpy as np
arr=np.array([1,2,3,])
new=arr.copy()
new[1]=100
print("array value is :",arr)
print("copy value is:",new)

array value is : [1 2 3]
copy value is: [  1 100   3]


In [ ]:
# view()
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("array value is :",arr)
print("view value is:",new)


array value is : [  1 100   3]
view value is: [  1 100   3]


In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr+=10
print("Updated array value is:",arr)

Updated array value is: [15 20 25 30 35 40]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

[-5 -5 -5 -5 -5]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))

[ 6 14 24 36 50]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

130


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(sum(arr))


45


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.std(arr))


2.581988897471611


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.min(arr))


1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.max(arr))


9


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(arr))


5.0


In [ ]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(arr))

[  1   3   4   4   7   8   9   9  11  34 141]


In [ ]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.unique(arr))

[  1   3   4   7   8   9  11  34 141]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)


(9,)
9
8
1
int64


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,2]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,2])


(2, 4)
2
2
4
[3 3]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,99,10,11,12,13,14,15])
print("Original Array:",arr)
new=arr.reshape(5,3)
print(new)

Original Array: [ 1  2  3  4  5  6  7  8 99 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]
 [10 11 12]
 [13 14 15]]
